-- Конвертация имён авторов в формат Фамилия И.О.
UPDATE articles SET authors = array_replace(authors, 'АЛЕКСАНДР ГРОМОВ', 'ГРОМОВ А.') WHERE 'АЛЕКСАНДР ГРОМОВ' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Август Тон', 'Тон А.') WHERE 'Август Тон' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Айдар Султанов', 'Султанов А.') WHERE 'Айдар Султанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Айк Керселян', 'Керселян А.') WHERE 'Айк Керселян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Айнур Ильшатович Шайдуллин', 'Шайдуллин А.И.') WHERE 'Айнур Ильшатович Шайдуллин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Айнур Шайдуллин', 'Шайдуллин А.И.') WHERE 'Айнур Шайдуллин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Айнур Шайдуллин', 'Шайдуллин А.И.') WHERE 'Айнур Шайдуллин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алан Байрамкулов', 'Байрамкулов А.') WHERE 'Алан Байрамкулов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Агафонов', 'Агафонов А.') WHERE 'Александр Агафонов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Александрович Маслов', 'Маслов А.А.') WHERE 'Александр Александрович Маслов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Александрович Ягельницкий', 'Ягельницкий А.А.') WHERE 'Александр Александрович Ягельницкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Ананьев', 'Ананьев А.') WHERE 'Александр Ананьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Андреевич Мальшаков', 'Мальшаков А.А.') WHERE 'Александр Андреевич Мальшаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Антонович Иванов', 'Иванов А.А.') WHERE 'Александр Антонович Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Верещагин', 'Верещагин А.') WHERE 'Александр Верещагин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Витальевич Разгильдеев', 'Разгильдеев А.В.') WHERE 'Александр Витальевич Разгильдеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Владимирович Сафонов', 'Сафонов А.В.') WHERE 'Александр Владимирович Сафонов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Гуна', 'Гуна А.') WHERE 'Александр Гуна' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Довгалюк', 'Довгалюк А.') WHERE 'Александр Довгалюк' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Заря', 'Заря А.') WHERE 'Александр Заря' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Зезекало', 'Зезекало А.') WHERE 'Александр Зезекало' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Игоревич Муранов', 'Муранов А.И.') WHERE 'Александр Игоревич Муранов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Казанцев', 'Казанцев А.') WHERE 'Александр Казанцев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Копылов', 'Копылов А.') WHERE 'Александр Копылов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Костин', 'Костин А.') WHERE 'Александр Костин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Кузнецов', 'Кузнецов А.') WHERE 'Александр Кузнецов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Латыев', 'Латыев А.') WHERE 'Александр Латыев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Малюшев', 'Малюшев А.') WHERE 'Александр Малюшев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Маслов', 'Маслов А.А.') WHERE 'Александр Маслов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Мличковский', 'Мличковский А.') WHERE 'Александр Мличковский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Разгильдеев', 'Разгильдеев А.В.') WHERE 'Александр Разгильдеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Робакидзе', 'Робакидзе А.') WHERE 'Александр Робакидзе' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Савельев', 'Савельев А.') WHERE 'Александр Савельев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Сергеев', 'Сергеев А.') WHERE 'Александр Сергеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Сергеевич Федоров', 'Федоров А.С.') WHERE 'Александр Сергеевич Федоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Соловьев', 'Соловьев А.') WHERE 'Александр Соловьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Трунин', 'Трунин А.') WHERE 'Александр Трунин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Федоров', 'Федоров А.С.') WHERE 'Александр Федоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Чупрунов', 'Чупрунов А.') WHERE 'Александр Чупрунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Чуряев', 'Чуряев А.') WHERE 'Александр Чуряев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Шварцер', 'Шварцер А.') WHERE 'Александр Шварцер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Шелкунов', 'Шелкунов А.') WHERE 'Александр Шелкунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Шмагин', 'Шмагин А.') WHERE 'Александр Шмагин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Щербаков', 'Щербаков А.') WHERE 'Александр Щербаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Мличковский', 'Мличковский А.') WHERE 'Александр Мличковский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александр Ягельницкий', 'Ягельницкий А.А.') WHERE 'Александр Ягельницкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александра Александровна Маковская', 'Маковская А.А.') WHERE 'Александра Александровна Маковская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александра Дмитриевна Софронова', 'Софронова А.Д.') WHERE 'Александра Дмитриевна Софронова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александра Козина', 'Козина А.') WHERE 'Александра Козина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александра Маковская', 'Маковская А.А.') WHERE 'Александра Маковская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Александра Улезко', 'Улезко А.') WHERE 'Александра Улезко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Агеев', 'Агеев А.') WHERE 'Алексей Агеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Акужинов', 'Акужинов А.С.') WHERE 'Алексей Акужинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Александрович Кулаков', 'Кулаков А.А.') WHERE 'Алексей Александрович Кулаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Алтухов', 'Алтухов А.') WHERE 'Алексей Алтухов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Аргунов', 'Аргунов А.') WHERE 'Алексей Аргунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Артюх', 'Артюх А.') WHERE 'Алексей Артюх' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Башарин', 'Башарин А.В.') WHERE 'Алексей Башарин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Белоликов', 'Белоликов А.') WHERE 'Алексей Белоликов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Борисенко', 'Борисенко А.') WHERE 'Алексей Борисенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Брысин', 'Брысин А.') WHERE 'Алексей Брысин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Вадимович Башарин', 'Башарин А.В.') WHERE 'Алексей Вадимович Башарин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Гаврилов', 'Гаврилов А.') WHERE 'Алексей Гаврилов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Елисеенко', 'Елисеенко А.') WHERE 'Алексей Елисеенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Ерофеев', 'Ерофеев А.') WHERE 'Алексей Ерофеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Иванов', 'Иванов А.') WHERE 'Алексей Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Качай', 'Качай А.') WHERE 'Алексей Качай' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Клементьев', 'Клементьев А.') WHERE 'Алексей Клементьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Мороз', 'Мороз А.') WHERE 'Алексей Мороз' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Никитин', 'Никитин А.') WHERE 'Алексей Никитин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Николаев', 'Николаев А.') WHERE 'Алексей Николаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Серыкович Акужинов', 'Акужинов А.С.') WHERE 'Алексей Серыкович Акужинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Сизов', 'Сизов А.') WHERE 'Алексей Сизов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Солохин', 'Солохин А.') WHERE 'Алексей Солохин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Станиславович Исполинов', 'Исполинов А.С.') WHERE 'Алексей Станиславович Исполинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Чередник', 'Чередник А.') WHERE 'Алексей Чередник' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Шарон', 'Шарон А.') WHERE 'Алексей Шарон' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Юрьевич Глазунов', 'Глазунов А.Ю.') WHERE 'Алексей Юрьевич Глазунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Юхнин', 'Юхнин А.') WHERE 'Алексей Юхнин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алексей Чунин', 'Чунин А.') WHERE 'Алексей Чунин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Али Арбиев', 'Арбиев А.') WHERE 'Али Арбиев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алина Андреевна Леонова', 'Леонова А.А.') WHERE 'Алина Андреевна Леонова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алина Безуглова', 'Безуглова А.') WHERE 'Алина Безуглова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алина Нечаева', 'Нечаева А.') WHERE 'Алина Нечаева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алина Сергеевна Прозорова', 'Прозорова А.С.') WHERE 'Алина Сергеевна Прозорова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алина Таманцева', 'Таманцева А.') WHERE 'Алина Таманцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алла Андреевна Лапшина', 'Лапшина А.А.') WHERE 'Алла Андреевна Лапшина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Альберт Григорян', 'Григорян А.') WHERE 'Альберт Григорян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Альбина Вугаровна Мамедалиева', 'Мамедалиева А.В.') WHERE 'Альбина Вугаровна Мамедалиева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алёна Козлова', 'Козлова А.С.') WHERE 'Алёна Козлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Алёна Сергеевна Козлова', 'Козлова А.С.') WHERE 'Алёна Сергеевна Козлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Беккер', 'Беккер А.') WHERE 'Анастасия Беккер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Велекжанина', 'Велекжанина А.') WHERE 'Анастасия Велекжанина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Горева', 'Горева А.') WHERE 'Анастасия Горева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Карпова', 'Карпова А.') WHERE 'Анастасия Карпова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Лысенко', 'Лысенко А.') WHERE 'Анастасия Лысенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Мехонцева', 'Мехонцева А.') WHERE 'Анастасия Мехонцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Пастухова', 'Пастухова А.') WHERE 'Анастасия Пастухова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Самотоина', 'Самотоина А.') WHERE 'Анастасия Самотоина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Сироткина', 'Сироткина А.') WHERE 'Анастасия Сироткина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Снопкова', 'Снопкова А.') WHERE 'Анастасия Снопкова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Тарбеева', 'Тарбеева А.') WHERE 'Анастасия Тарбеева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Тюняева', 'Тюняева А.') WHERE 'Анастасия Тюняева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Хряпченко', 'Хряпченко А.') WHERE 'Анастасия Хряпченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Чагина', 'Чагина А.') WHERE 'Анастасия Чагина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Шамшина', 'Шамшина А.') WHERE 'Анастасия Шамшина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анастасия Щукина', 'Щукина А.') WHERE 'Анастасия Щукина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анатолий Андреевич Борисов', 'Борисов А.А.') WHERE 'Анатолий Андреевич Борисов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ангелина Севостьянова', 'Севостьянова А.') WHERE 'Ангелина Севостьянова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Александрович Панов', 'Панов А.А.') WHERE 'Андрей Александрович Панов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Анатольевич Павлов', 'Павлов А.А.') WHERE 'Андрей Анатольевич Павлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Андреевич Громов', 'Громов А.А.') WHERE 'Андрей Андреевич Громов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Владимирович Егоров', 'Егоров А.В.') WHERE 'Андрей Владимирович Егоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Габов', 'Габов А.') WHERE 'Андрей Габов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Громов', 'Громов А.А.') WHERE 'Андрей Громов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Евгеньевич Быков', 'Быков А.Е.') WHERE 'Андрей Евгеньевич Быков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Егоров', 'Егоров А.В.') WHERE 'Андрей Егоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Касьянов', 'Касьянов А.') WHERE 'Андрей Касьянов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Комаров', 'Комаров А.') WHERE 'Андрей Комаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Олегович Рыбалов', 'Рыбалов А.О.') WHERE 'Андрей Олегович Рыбалов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Павлов', 'Павлов А.А.') WHERE 'Андрей Павлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Панов', 'Панов А.А.') WHERE 'Андрей Панов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Рыбалов', 'Рыбалов А.О.') WHERE 'Андрей Рыбалов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Чернов', 'Чернов А.') WHERE 'Андрей Чернов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Черноус', 'Черноус А.') WHERE 'Андрей Черноус' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Шафранов', 'Шафранов А.') WHERE 'Андрей Шафранов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Юдин', 'Юдин А.') WHERE 'Андрей Юдин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Юрьевич Каратеев', 'Каратеев А.Ю.') WHERE 'Андрей Юрьевич Каратеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Андрей Ерофицкий', 'Ерофицкий А.') WHERE 'Андрей Ерофицкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Акифьева', 'Акифьева А.') WHERE 'Анна Акифьева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Алдошкина', 'Алдошкина А.') WHERE 'Анна Алдошкина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Александровна Алексеева', 'Алексеева А.А.') WHERE 'Анна Александровна Алексеева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Александровна Смола', 'Смола А.А.') WHERE 'Анна Александровна Смола' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Алексеевна Волкова', 'Волкова А.А.') WHERE 'Анна Алексеевна Волкова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Анатольевна Маркелова', 'Маркелова А.А.') WHERE 'Анна Анатольевна Маркелова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Архипова', 'Архипова А.') WHERE 'Анна Архипова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Береснева', 'Береснева А.') WHERE 'Анна Береснева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Васильева', 'Васильева А.') WHERE 'Анна Васильева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Вячеславовна Иноземцева', 'Иноземцева А.В.') WHERE 'Анна Вячеславовна Иноземцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Иванова', 'Иванова А.') WHERE 'Анна Иванова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Карачун', 'Карачун А.') WHERE 'Анна Карачун' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Маркелова', 'Маркелова А.А.') WHERE 'Анна Маркелова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Новицкая', 'Новицкая А.') WHERE 'Анна Новицкая' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Скорова', 'Скорова А.') WHERE 'Анна Скорова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анна Смола', 'Смола А.А.') WHERE 'Анна Смола' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Анри Капитан', 'Капитан А.') WHERE 'Анри Капитан' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Александрович Иванов', 'Иванов А.А.') WHERE 'Антон Александрович Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Александрович Никифоров', 'Никифоров А.А.') WHERE 'Антон Александрович Никифоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Асосков', 'Асосков А.') WHERE 'Антон Асосков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Валерьевич Ильин', 'Ильин А.В.') WHERE 'Антон Валерьевич Ильин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Иванов', 'Иванов А.А.') WHERE 'Антон Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Ильин', 'Ильин А.В.') WHERE 'Антон Ильин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Комогоров', 'Комогоров А.') WHERE 'Антон Комогоров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Мертвищев', 'Мертвищев А.') WHERE 'Антон Мертвищев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Мухаметшин', 'Мухаметшин А.') WHERE 'Антон Мухаметшин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Мыкольников', 'Мыкольников А.') WHERE 'Антон Мыкольников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Прошин', 'Прошин А.') WHERE 'Антон Прошин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Руднев', 'Руднев А.') WHERE 'Антон Руднев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Рудоквас', 'Рудоквас А.') WHERE 'Антон Рудоквас' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Томсинов', 'Томсинов А.') WHERE 'Антон Томсинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Чухнаков', 'Чухнаков А.') WHERE 'Антон Чухнаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антон Яхимович', 'Яхимович А.') WHERE 'Антон Яхимович' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Антонио Альмендрос Руиз', 'Руиз А.А.') WHERE 'Антонио Альмендрос Руиз' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Арина Никулушкина', 'Никулушкина А.') WHERE 'Арина Никулушкина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Аркадий Горченко', 'Горченко А.') WHERE 'Аркадий Горченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Арсений Янович Быстров', 'Быстров А.Я.') WHERE 'Арсений Янович Быстров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артак Размикович Тигранян', 'Тигранян А.Р.') WHERE 'Артак Размикович Тигранян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Бродский', 'Бродский А.') WHERE 'Артем Бродский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Георгиевич Карапетов', 'Карапетов А.Г.') WHERE 'Артем Георгиевич Карапетов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Евсеев', 'Евсеев А.') WHERE 'Артем Евсеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Крицкий', 'Крицкий А.') WHERE 'Артем Крицкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Савилов', 'Савилов А.') WHERE 'Артем Савилов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артем Свистов', 'Свистов А.') WHERE 'Артем Свистов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артур Стариков', 'Стариков А.') WHERE 'Артур Стариков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артур Черныхов', 'Черныхов А.') WHERE 'Артур Черныхов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артур Швайка', 'Швайка А.') WHERE 'Артур Швайка' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Бек', 'Бек А.') WHERE 'Артём Бек' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Васильевич Сафьянников', 'Сафьянников А.В.') WHERE 'Артём Васильевич Сафьянников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Карапетов', 'Карапетов А.') WHERE 'Артём Карапетов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Копылов', 'Копылов А.') WHERE 'Артём Копылов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Сергеевич Райников', 'Райников А.С.') WHERE 'Артём Сергеевич Райников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Сирота', 'Сирота А.') WHERE 'Артём Сирота' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Артём Янович Берлин', 'Берлин А.Я.') WHERE 'Артём Янович Берлин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Арутюн Вагеевич Саркисян', 'Саркисян А.В.') WHERE 'Арутюн Вагеевич Саркисян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Арутюн Саркисян', 'Саркисян А.В.') WHERE 'Арутюн Саркисян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Бернхарт Виндшайд', 'Виндшайд Б.') WHERE 'Бернхарт Виндшайд' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Билал Курбанов', 'Курбанов Б.') WHERE 'Билал Курбанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Борис Борисович Воронин', 'Воронин Б.Б.') WHERE 'Борис Борисович Воронин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Борис Брук', 'Брук Б.') WHERE 'Борис Брук' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Булат Цыбикжапов', 'Цыбикжапов Б.') WHERE 'Булат Цыбикжапов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Александрович Алексеев', 'Алексеев В.А.') WHERE 'Вадим Александрович Алексеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Алексеев', 'Алексеев В.А.') WHERE 'Вадим Алексеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Анатольевич Белов', 'Белов В.А.') WHERE 'Вадим Анатольевич Белов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Винник', 'Винник В.') WHERE 'Вадим Винник' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Инсаров', 'Инсаров В.') WHERE 'Вадим Инсаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Рак', 'Рак В.') WHERE 'Вадим Рак' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вадим Фогель', 'Фогель В.') WHERE 'Вадим Фогель' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валентина Александровна Родикова', 'Родикова В.А.') WHERE 'Валентина Александровна Родикова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валентина Фролова', 'Фролова В.') WHERE 'Валентина Фролова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валериан Зазаевич Мамагеишвили', 'Мамагеишвили В.З.') WHERE 'Валериан Зазаевич Мамагеишвили' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валериан Мамагеишвили', 'Мамагеишвили В.З.') WHERE 'Валериан Мамагеишвили' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валерий Белов', 'Белов В.') WHERE 'Валерий Белов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валерия Асоскова', 'Асоскова В.') WHERE 'Валерия Асоскова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Валерия Обухова', 'Обухова В.') WHERE 'Валерия Обухова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Василий Андреевич Лаптев', 'Лаптев В.А.') WHERE 'Василий Андреевич Лаптев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Василий Константинович Захаров', 'Захаров В.К.') WHERE 'Василий Константинович Захаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вера Алейникова', 'Алейникова В.') WHERE 'Вера Алейникова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вероника Величко', 'Величко В.') WHERE 'Вероника Величко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Валентинович Бациев', 'Бациев В.В.') WHERE 'Виктор Валентинович Бациев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Вяткин', 'Вяткин В.') WHERE 'Виктор Вяткин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Георгиевич Домшенко', 'Домшенко В.Г.') WHERE 'Виктор Георгиевич Домшенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Гербутов', 'Гербутов В.С.') WHERE 'Виктор Гербутов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Домшенко', 'Домшенко В.Г.') WHERE 'Виктор Домшенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Седнев', 'Седнев В.') WHERE 'Виктор Седнев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Сорокин', 'Сорокин В.') WHERE 'Виктор Сорокин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Станиславович Гербутов', 'Гербутов В.С.') WHERE 'Виктор Станиславович Гербутов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктор Филипенко', 'Филипенко В.') WHERE 'Виктор Филипенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктория Бочкарева', 'Бочкарева В.') WHERE 'Виктория Бочкарева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктория Дергунова', 'Дергунова В.') WHERE 'Виктория Дергунова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктория Зубарева', 'Зубарева В.') WHERE 'Виктория Зубарева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виктория Дергунова', 'Дергунова В.') WHERE 'Виктория Дергунова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виталий Калятин', 'Калятин В.О.') WHERE 'Виталий Калятин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Виталий Олегович Калятин', 'Калятин В.О.') WHERE 'Виталий Олегович Калятин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Александрович Корнеев', 'Корнеев В.А.') WHERE 'Владимир Александрович Корнеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Багаев', 'Багаев В.') WHERE 'Владимир Багаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Белявцев', 'Белявцев В.') WHERE 'Владимир Белявцев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Васнёв', 'Васнёв В.') WHERE 'Владимир Васнёв' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Владимирович Ярков', 'Ярков В.В.') WHERE 'Владимир Владимирович Ярков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Загнетин', 'Загнетин В.') WHERE 'Владимир Загнетин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Килинкаров', 'Килинкаров В.') WHERE 'Владимир Килинкаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Клименко', 'Клименко В.') WHERE 'Владимир Клименко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Косцов', 'Косцов В.') WHERE 'Владимир Косцов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Липавский', 'Липавский В.') WHERE 'Владимир Липавский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Михайлович Будилов', 'Будилов В.М.') WHERE 'Владимир Михайлович Будилов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Мымрин', 'Мымрин В.') WHERE 'Владимир Мымрин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Сафонов', 'Сафонов В.') WHERE 'Владимир Сафонов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владимир Ярков', 'Ярков В.В.') WHERE 'Владимир Ярков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Андреевич Молчанов', 'Молчанов В.А.') WHERE 'Владислав Андреевич Молчанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Аристов', 'Аристов В.') WHERE 'Владислав Аристов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Валерьевич Старженецкий', 'Старженецкий В.В.') WHERE 'Владислав Валерьевич Старженецкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Гридасов', 'Гридасов В.') WHERE 'Владислав Гридасов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Зотов', 'Зотов В.') WHERE 'Владислав Зотов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Костко', 'Костко В.С.') WHERE 'Владислав Костко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Култаев', 'Култаев В.') WHERE 'Владислав Култаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Максимович Цуркан', 'Цуркан В.М.') WHERE 'Владислав Максимович Цуркан' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Осипов', 'Осипов В.') WHERE 'Владислав Осипов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Савиных', 'Савиных В.') WHERE 'Владислав Савиных' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Сергеевич Костко', 'Костко В.С.') WHERE 'Владислав Сергеевич Костко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислав Старженецкий', 'Старженецкий В.В.') WHERE 'Владислав Старженецкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Владислава Сергеевна Михайлова', 'Михайлова В.С.') WHERE 'Владислава Сергеевна Михайлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Всеволод Байбак', 'Байбак В.') WHERE 'Всеволод Байбак' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Всеволод Владимирович Аргунов', 'Аргунов В.В.') WHERE 'Всеволод Владимирович Аргунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вячеслав Бирклей', 'Бирклей В.') WHERE 'Вячеслав Бирклей' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вячеслав Григорьев', 'Григорьев В.И.') WHERE 'Вячеслав Григорьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вячеслав Иваненко', 'Иваненко В.') WHERE 'Вячеслав Иваненко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Вячеслав Игоревич Григорьев', 'Григорьев В.И.') WHERE 'Вячеслав Игоревич Григорьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Гадис Гаджиев', 'Гаджиев Г.') WHERE 'Гадис Гаджиев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Галина Петровна Хованская', 'Хованская Г.П.') WHERE 'Галина Петровна Хованская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Геннадий Васильев', 'Васильев Г.С.') WHERE 'Геннадий Васильев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Геннадий Есаков', 'Есаков Г.') WHERE 'Геннадий Есаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Геннадий Сергеевич Васильев', 'Васильев Г.С.') WHERE 'Геннадий Сергеевич Васильев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Геннадий Соловьев', 'Соловьев Г.') WHERE 'Геннадий Соловьев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Георгий Адам', 'Адам Г.') WHERE 'Георгий Адам' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Георгий Викторович Цепов', 'Цепов Г.В.') WHERE 'Георгий Викторович Цепов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Георгий Олегович Сергеев', 'Сергеев Г.О.') WHERE 'Георгий Олегович Сергеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Глеб Сударев', 'Сударев Г.') WHERE 'Глеб Сударев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Григорий Андреевич Скутин', 'Скутин Г.А.') WHERE 'Григорий Андреевич Скутин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Григорий Галкин', 'Галкин Г.') WHERE 'Григорий Галкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Гурген Вазгенович Айрапетян', 'Айрапетян Г.В.') WHERE 'Гурген Вазгенович Айрапетян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дамир Валеев', 'Валеев Д.') WHERE 'Дамир Валеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Борейшо', 'Борейшо Д.В.') WHERE 'Даниил Борейшо' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Борисович Володарский', 'Володарский Д.Б.') WHERE 'Даниил Борисович Володарский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Владимирович Борейшо', 'Борейшо Д.В.') WHERE 'Даниил Владимирович Борейшо' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Волков', 'Волков Д.') WHERE 'Даниил Волков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Мамбетов', 'Мамбетов Д.') WHERE 'Даниил Мамбетов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Олегович Тузов', 'Тузов Д.О.') WHERE 'Даниил Олегович Тузов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Савченко', 'Савченко Д.') WHERE 'Даниил Савченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Тузов', 'Тузов Д.О.') WHERE 'Даниил Тузов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Шаляев', 'Шаляев Д.Ю.') WHERE 'Даниил Шаляев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Даниил Юрьевич Шаляев', 'Шаляев Д.Ю.') WHERE 'Даниил Юрьевич Шаляев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Данил Дрозд', 'Дрозд Д.') WHERE 'Данил Дрозд' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Данил Олегович Иванов', 'Иванов Д.О.') WHERE 'Данил Олегович Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дария Жестовская', 'Жестовская Д.') WHERE 'Дария Жестовская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Александровна Фаталиева', 'Фаталиева Д.А.') WHERE 'Дарья Александровна Фаталиева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Булаева', 'Булаева Д.') WHERE 'Дарья Булаева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Ждан-Пушкина', 'Ждан-Пушкина Д.') WHERE 'Дарья Ждан-Пушкина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Иванова', 'Иванова Д.') WHERE 'Дарья Иванова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Куклина', 'Куклина Д.') WHERE 'Дарья Куклина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Панова', 'Панова Д.') WHERE 'Дарья Панова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарья Сергеевна Петрова', 'Петрова Д.С.') WHERE 'Дарья Сергеевна Петрова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дарьяна Епихина', 'Епихина Д.') WHERE 'Дарьяна Епихина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Денис Андреевич Тварковский', 'Тварковский Д.А.') WHERE 'Денис Андреевич Тварковский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Денис Беккер', 'Беккер Д.') WHERE 'Денис Беккер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Денис Быканов', 'Быканов Д.') WHERE 'Денис Быканов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Денис Доротенко', 'Доротенко Д.') WHERE 'Денис Доротенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Денис Соков', 'Соков Д.') WHERE 'Денис Соков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Диана Григорьян', 'Григорьян Д.') WHERE 'Диана Григорьян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Диана Османова', 'Османова Д.') WHERE 'Диана Османова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Абушенко', 'Абушенко Д.Б.') WHERE 'Дмитрий Абушенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Александрович Купцов', 'Купцов Д.А.') WHERE 'Дмитрий Александрович Купцов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Анатольевич Скугаревский', 'Скугаревский Д.А.') WHERE 'Дмитрий Анатольевич Скугаревский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Анатольевич Чваненко', 'Чваненко Д.А.') WHERE 'Дмитрий Анатольевич Чваненко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Арнаутов', 'Арнаутов Д.') WHERE 'Дмитрий Арнаутов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Бойков', 'Бойков Д.') WHERE 'Дмитрий Бойков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Борисович Абушенко', 'Абушенко Д.Б.') WHERE 'Дмитрий Борисович Абушенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Борисович Давыдов', 'Давыдов Д.Б.') WHERE 'Дмитрий Борисович Давыдов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Викторович Тариканов', 'Тариканов Д.В.') WHERE 'Дмитрий Викторович Тариканов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Глоов', 'Глоов Д.') WHERE 'Дмитрий Глоов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Горчаков', 'Горчаков Д.') WHERE 'Дмитрий Горчаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Громов', 'Громов Д.') WHERE 'Дмитрий Громов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Ильин', 'Ильин Д.') WHERE 'Дмитрий Ильин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Лоренц', 'Лоренц Д.') WHERE 'Дмитрий Лоренц' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Луданин', 'Луданин Д.') WHERE 'Дмитрий Луданин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Мальбин', 'Мальбин Д.') WHERE 'Дмитрий Мальбин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Некрестьянов', 'Некрестьянов Д.') WHERE 'Дмитрий Некрестьянов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Николаевич Салмин', 'Салмин Д.Н.') WHERE 'Дмитрий Николаевич Салмин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Смольников', 'Смольников Д.') WHERE 'Дмитрий Смольников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Степанов', 'Степанов Д.') WHERE 'Дмитрий Степанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Тариканов', 'Тариканов Д.В.') WHERE 'Дмитрий Тариканов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Чваненко', 'Чваненко Д.А.') WHERE 'Дмитрий Чваненко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Шнайдман', 'Шнайдман Д.') WHERE 'Дмитрий Шнайдман' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Штефан', 'Штефан Д.') WHERE 'Дмитрий Штефан' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дмитрий Щепин', 'Щепин Д.') WHERE 'Дмитрий Щепин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Донат Краснов', 'Краснов Д.') WHERE 'Донат Краснов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Думан Алекперов', 'Алекперов Д.') WHERE 'Думан Алекперов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Дэниэл Фарбер', 'Фарбер Д.') WHERE 'Дэниэл Фарбер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Александрович Некеров', 'Некеров Е.А.') WHERE 'Евгений Александрович Некеров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Алексеевич Суханов', 'Суханов Е.А.') WHERE 'Евгений Алексеевич Суханов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Воронин', 'Воронин Е.') WHERE 'Евгений Воронин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Гаврилов', 'Гаврилов Е.') WHERE 'Евгений Гаврилов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Голованов', 'Голованов Е.') WHERE 'Евгений Голованов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Горбунов', 'Горбунов Е.Ю.') WHERE 'Евгений Горбунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Михайлов', 'Михайлов Е.') WHERE 'Евгений Михайлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Николаевич Акимов', 'Акимов Е.Н.') WHERE 'Евгений Николаевич Акимов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Петров', 'Петров Е.') WHERE 'Евгений Петров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Радкевич', 'Радкевич Е.') WHERE 'Евгений Радкевич' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Суворов', 'Суворов Е.') WHERE 'Евгений Суворов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Суров', 'Суров Е.') WHERE 'Евгений Суров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Фокин', 'Фокин Е.') WHERE 'Евгений Фокин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгений Юрьевич Горбунов', 'Горбунов Е.Ю.') WHERE 'Евгений Юрьевич Горбунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгения Кузьмичева', 'Кузьмичева Е.') WHERE 'Евгения Кузьмичева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгения Курзински-Сингер', 'Курзински-Сингер Е.') WHERE 'Евгения Курзински-Сингер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Евгения Юрьевна Борзило', 'Борзило Е.Ю.') WHERE 'Евгения Юрьевна Борзило' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Егор Алексеевич Логинов', 'Логинов Е.А.') WHERE 'Егор Алексеевич Логинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Егор Иванов', 'Иванов Е.') WHERE 'Егор Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Егор Логинов', 'Логинов Е.А.') WHERE 'Егор Логинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Автонова', 'Автонова Е.') WHERE 'Екатерина Автонова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Александровна Смирнова', 'Смирнова Е.А.') WHERE 'Екатерина Александровна Смирнова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Боннер', 'Боннер Е.') WHERE 'Екатерина Боннер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Брижик', 'Брижик Е.') WHERE 'Екатерина Брижик' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Валерьевна Бибикова', 'Бибикова Е.В.') WHERE 'Екатерина Валерьевна Бибикова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Мишина', 'Мишина Е.') WHERE 'Екатерина Мишина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Окань', 'Окань Е.') WHERE 'Екатерина Окань' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Папченкова', 'Папченкова Е.') WHERE 'Екатерина Папченкова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Фетисова', 'Фетисова Е.') WHERE 'Екатерина Фетисова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Юлова', 'Юлова Е.') WHERE 'Екатерина Юлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Екатерина Юрьевна Иванова', 'Иванова Е.Ю.') WHERE 'Екатерина Юрьевна Иванова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Александровна Борисова', 'Борисова Е.А.') WHERE 'Елена Александровна Борисова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Александровна Останина', 'Останина Е.А.') WHERE 'Елена Александровна Останина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Александровна Павлова', 'Павлова Е.А.') WHERE 'Елена Александровна Павлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Алексеевна Шеломенцева', 'Шеломенцева Е.А.') WHERE 'Елена Алексеевна Шеломенцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Анатольевна Михайлова', 'Михайлова Е.А.') WHERE 'Елена Анатольевна Михайлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Королева', 'Королева Е.') WHERE 'Елена Королева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Леонтьева', 'Леонтьева Е.') WHERE 'Елена Леонтьева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Михайловна Андреева', 'Андреева Е.М.') WHERE 'Елена Михайловна Андреева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Михайловна Ключарева', 'Ключарева Е.М.') WHERE 'Елена Михайловна Ключарева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Мохова', 'Мохова Е.') WHERE 'Елена Мохова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Останина', 'Останина Е.А.') WHERE 'Елена Останина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Поветкина', 'Поветкина Е.') WHERE 'Елена Поветкина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елена Широкова', 'Широкова Е.') WHERE 'Елена Широкова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елизавета Дмитриевна Тимербулатова', 'Тимербулатова Е.Д.') WHERE 'Елизавета Дмитриевна Тимербулатова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елизавета Зотова', 'Зотова Е.') WHERE 'Елизавета Зотова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Елизавета Олеговна Брежнева', 'Брежнева Е.О.') WHERE 'Елизавета Олеговна Брежнева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ибрагим Аллахвердиев', 'Аллахвердиев И.') WHERE 'Ибрагим Аллахвердиев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Агафонов', 'Агафонов И.') WHERE 'Иван Агафонов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Андреевич Алямкин', 'Алямкин И.А.') WHERE 'Иван Андреевич Алямкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Белоусов', 'Белоусов И.') WHERE 'Иван Белоусов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Васильевич Стасюк', 'Стасюк И.В.') WHERE 'Иван Васильевич Стасюк' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Григорьевич Деркач', 'Деркач И.Г.') WHERE 'Иван Григорьевич Деркач' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Деркач', 'Деркач И.Г.') WHERE 'Иван Деркач' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Дмитриевич Ищенко', 'Ищенко И.Д.') WHERE 'Иван Дмитриевич Ищенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Кобченко', 'Кобченко И.') WHERE 'Иван Кобченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Константинович Тебенёв', 'Тебенёв И.К.') WHERE 'Иван Константинович Тебенёв' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Кропачев', 'Кропачев И.') WHERE 'Иван Кропачев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Николаевич Белов', 'Белов И.Н.') WHERE 'Иван Николаевич Белов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Подкопалов', 'Подкопалов И.') WHERE 'Иван Подкопалов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Сергеевич Чупрунов', 'Чупрунов И.С.') WHERE 'Иван Сергеевич Чупрунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Стасюк', 'Стасюк И.В.') WHERE 'Иван Стасюк' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Тебенёв', 'Тебенёв И.К.') WHERE 'Иван Тебенёв' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Иван Чупрунов', 'Чупрунов И.С.') WHERE 'Иван Чупрунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ившина Анна', 'Анна И.') WHERE 'Ившина Анна' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Антюшин', 'Антюшин И.') WHERE 'Игорь Антюшин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Архипов', 'Архипов И.') WHERE 'Игорь Архипов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Дергунов', 'Дергунов И.') WHERE 'Игорь Дергунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Приходько', 'Приходько И.') WHERE 'Игорь Приходько' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Ренц', 'Ренц И.') WHERE 'Игорь Ренц' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Сергеевич Ляшенко', 'Ляшенко И.С.') WHERE 'Игорь Сергеевич Ляшенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Толмачёв', 'Толмачёв И.') WHERE 'Игорь Толмачёв' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Игорь Ястржембский', 'Ястржембский И.') WHERE 'Игорь Ястржембский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ильнар Абдулов', 'Абдулов И.') WHERE 'Ильнар Абдулов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Валерьевич Репин', 'Репин И.В.') WHERE 'Илья Валерьевич Репин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Гаркунов', 'Гаркунов И.') WHERE 'Илья Гаркунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Зикун', 'Зикун И.') WHERE 'Илья Зикун' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Игоревич Писаревский', 'Писаревский И.И.') WHERE 'Илья Игоревич Писаревский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Киселев', 'Киселев И.') WHERE 'Илья Киселев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Кокорин', 'Кокорин И.') WHERE 'Илья Кокорин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Михайлович Шевченко', 'Шевченко И.М.') WHERE 'Илья Михайлович Шевченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Папилин', 'Папилин И.') WHERE 'Илья Папилин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Петрановский', 'Петрановский И.') WHERE 'Илья Петрановский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Илья Шевченко', 'Шевченко И.М.') WHERE 'Илья Шевченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Инна Панова', 'Панова И.') WHERE 'Инна Панова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Ивлева', 'Ивлева И.') WHERE 'Ирина Ивлева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Карасева', 'Карасева И.') WHERE 'Ирина Карасева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Кашкарова', 'Кашкарова И.Н.') WHERE 'Ирина Кашкарова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Николаевна Кашкарова', 'Кашкарова И.Н.') WHERE 'Ирина Николаевна Кашкарова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Сацук', 'Сацук И.') WHERE 'Ирина Сацук' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Сергеевна Шиткина', 'Шиткина И.С.') WHERE 'Ирина Сергеевна Шиткина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Фаст', 'Фаст И.') WHERE 'Ирина Фаст' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ирина Чердинцева', 'Чердинцева И.') WHERE 'Ирина Чердинцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Исмаил Зиядинович Халифаев', 'Халифаев И.З.') WHERE 'Исмаил Зиядинович Халифаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Исмаил Халифаев', 'Халифаев И.З.') WHERE 'Исмаил Халифаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Карина Ростовцева', 'Ростовцева К.') WHERE 'Карина Ростовцева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Карина Фаттахова', 'Фаттахова К.') WHERE 'Карина Фаттахова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Андреевич Новиков', 'Новиков К.А.') WHERE 'Кирилл Андреевич Новиков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Андреевич Писенко', 'Писенко К.А.') WHERE 'Кирилл Андреевич Писенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Зимарев', 'Зимарев К.') WHERE 'Кирилл Зимарев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Константинович Палушин', 'Палушин К.К.') WHERE 'Кирилл Константинович Палушин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Митягин', 'Митягин К.') WHERE 'Кирилл Митягин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Михайлов', 'Михайлов К.') WHERE 'Кирилл Михайлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Нам', 'Нам К.') WHERE 'Кирилл Нам' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Новиков', 'Новиков К.А.') WHERE 'Кирилл Новиков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Тарасов', 'Тарасов К.') WHERE 'Кирилл Тарасов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Чоракаев', 'Чоракаев К.') WHERE 'Кирилл Чоракаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кирилл Чухалдин', 'Чухалдин К.') WHERE 'Кирилл Чухалдин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Валерьевич Геец', 'Геец К.В.') WHERE 'Константин Валерьевич Геец' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Владимирович Гричанин', 'Гричанин К.В.') WHERE 'Константин Владимирович Гричанин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Геец', 'Геец К.В.') WHERE 'Константин Геец' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Гницевич', 'Гницевич К.') WHERE 'Константин Гницевич' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Гричанин', 'Гричанин К.В.') WHERE 'Константин Гричанин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Гультяев', 'Гультяев К.') WHERE 'Константин Гультяев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Киктенко', 'Киктенко К.') WHERE 'Константин Киктенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Павлович Саврыга', 'Саврыга К.П.') WHERE 'Константин Павлович Саврыга' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Савин', 'Савин К.') WHERE 'Константин Савин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Саврыга', 'Саврыга К.П.') WHERE 'Константин Саврыга' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Скловский', 'Скловский К.') WHERE 'Константин Скловский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Константин Шемякин', 'Шемякин К.') WHERE 'Константин Шемякин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кристина Гурылева', 'Гурылева К.') WHERE 'Кристина Гурылева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кристина Дронова', 'Дронова К.') WHERE 'Кристина Дронова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Кристина Юркова', 'Юркова К.') WHERE 'Кристина Юркова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ксения Александровна Усачева', 'Усачева К.А.') WHERE 'Ксения Александровна Усачева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ксения Усачева', 'Усачева К.А.') WHERE 'Ксения Усачева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ксения Брикса', 'Брикса К.') WHERE 'Ксения Брикса' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ларс ван Влит', 'Влит Л.в.') WHERE 'Ларс ван Влит' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Латыев Александр Николаевич', 'Николаевич Л.А.') WHERE 'Латыев Александр Николаевич' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Леонид Бандорин', 'Бандорин Л.') WHERE 'Леонид Бандорин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Леонид Ходасевич', 'Ходасевич Л.') WHERE 'Леонид Ходасевич' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Лина Макаренко', 'Макаренко Л.') WHERE 'Лина Макаренко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Лусине Арутюнян', 'Арутюнян Л.') WHERE 'Лусине Арутюнян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Любовь Дорошенко', 'Дорошенко Л.') WHERE 'Любовь Дорошенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Людмила Степанова', 'Степанова Л.') WHERE 'Людмила Степанова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Людмила Яблокова', 'Яблокова Л.') WHERE 'Людмила Яблокова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Алпатов', 'Алпатов М.') WHERE 'Максим Алпатов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Андреев', 'Андреев М.') WHERE 'Максим Андреев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Владимирович Марасанов', 'Марасанов М.В.') WHERE 'Максим Владимирович Марасанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Иванович Лухманов', 'Лухманов М.И.') WHERE 'Максим Иванович Лухманов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Кратенко', 'Кратенко М.') WHERE 'Максим Кратенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Лухманов', 'Лухманов М.И.') WHERE 'Максим Лухманов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Марасанов', 'Марасанов М.В.') WHERE 'Максим Марасанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Обухов', 'Обухов М.') WHERE 'Максим Обухов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Рапопорт', 'Рапопорт М.') WHERE 'Максим Рапопорт' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Федоренко', 'Федоренко М.') WHERE 'Максим Федоренко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Максим Юрьевич До', 'До М.Ю.') WHERE 'Максим Юрьевич До' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Марат Фаттахов', 'Фаттахов М.') WHERE 'Марат Фаттахов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Маргарита Дробышевская', 'Дробышевская М.') WHERE 'Маргарита Дробышевская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Маргарита Клементьева', 'Клементьева М.') WHERE 'Маргарита Клементьева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Марина Нохрина', 'Нохрина М.') WHERE 'Марина Нохрина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Марина Рожкова', 'Рожкова М.') WHERE 'Марина Рожкова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Александрова', 'Александрова М.А.') WHERE 'Мария Александрова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Александровна Александрова', 'Александрова М.А.') WHERE 'Мария Александровна Александрова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Андреевна Ерохова', 'Ерохова М.А.') WHERE 'Мария Андреевна Ерохова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Белова', 'Белова М.') WHERE 'Мария Белова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Ерохова', 'Ерохова М.А.') WHERE 'Мария Ерохова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Кокорина', 'Кокорина М.') WHERE 'Мария Кокорина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Кольздорф', 'Кольздорф М.') WHERE 'Мария Кольздорф' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Михайловна Александрова', 'Александрова М.М.') WHERE 'Мария Михайловна Александрова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Мыцикова', 'Мыцикова М.') WHERE 'Мария Мыцикова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Пляцидевская', 'Пляцидевская М.') WHERE 'Мария Пляцидевская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Прибыткова', 'Прибыткова М.') WHERE 'Мария Прибыткова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Радецкая', 'Радецкая М.') WHERE 'Мария Радецкая' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Мария Шабалина', 'Шабалина М.') WHERE 'Мария Шабалина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Марьяна Ламова', 'Ламова М.') WHERE 'Марьяна Ламова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Матвей Олегович Киселев', 'Киселев М.О.') WHERE 'Матвей Олегович Киселев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Бандо', 'Бандо М.') WHERE 'Михаил Бандо' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Веселов', 'Веселов М.') WHERE 'Михаил Веселов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Волчанский', 'Волчанский М.') WHERE 'Михаил Волчанский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Гальперин', 'Гальперин М.Л.') WHERE 'Михаил Гальперин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Жужжалов', 'Жужжалов М.') WHERE 'Михаил Жужжалов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Зиновьевич Шварц', 'Шварц М.З.') WHERE 'Михаил Зиновьевич Шварц' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Ковалерчик', 'Ковалерчик М.') WHERE 'Михаил Ковалерчик' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Львович Гальперин', 'Гальперин М.Л.') WHERE 'Михаил Львович Гальперин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Прокопец', 'Прокопец М.') WHERE 'Михаил Прокопец' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Самойлов', 'Самойлов М.') WHERE 'Михаил Самойлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Тягусов', 'Тягусов М.') WHERE 'Михаил Тягусов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Церковников', 'Церковников М.') WHERE 'Михаил Церковников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Чикунов', 'Чикунов М.') WHERE 'Михаил Чикунов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Михаил Чуприков', 'Чуприков М.') WHERE 'Михаил Чуприков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Надежда Филипенко', 'Филипенко Н.') WHERE 'Надежда Филипенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталия Рассказова', 'Рассказова Н.') WHERE 'Наталия Рассказова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Архипова', 'Архипова Н.') WHERE 'Наталья Архипова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Германовна Нарышева', 'Нарышева Н.Г.') WHERE 'Наталья Германовна Нарышева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Гуляева', 'Гуляева Н.') WHERE 'Наталья Гуляева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Кантор', 'Кантор Н.') WHERE 'Наталья Кантор' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Павлова', 'Павлова Н.') WHERE 'Наталья Павлова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Спиридонова', 'Спиридонова Н.') WHERE 'Наталья Спиридонова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Наталья Тололаева', 'Тололаева Н.') WHERE 'Наталья Тололаева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Александрович Кастерин', 'Кастерин Н.А.') WHERE 'Никита Александрович Кастерин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Анатольевич Павлов', 'Павлов Н.А.') WHERE 'Никита Анатольевич Павлов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Васильев', 'Васильев Н.') WHERE 'Никита Васильев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Виленский', 'Виленский Н.') WHERE 'Никита Виленский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Витальевич Иванов', 'Иванов Н.В.') WHERE 'Никита Витальевич Иванов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Владиславович Резанов', 'Резанов Н.В.') WHERE 'Никита Владиславович Резанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Гущин', 'Гущин Н.') WHERE 'Никита Гущин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Игоревич Трубин', 'Трубин Н.И.') WHERE 'Никита Игоревич Трубин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Кастерин', 'Кастерин Н.А.') WHERE 'Никита Кастерин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Максимович Ржанов', 'Ржанов Н.М.') WHERE 'Никита Максимович Ржанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Николаев', 'Николаев Н.') WHERE 'Никита Николаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Рогожин', 'Рогожин Н.') WHERE 'Никита Рогожин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Сутормин', 'Сутормин Н.') WHERE 'Никита Сутормин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Теплов', 'Теплов Н.') WHERE 'Никита Теплов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Ульянов', 'Ульянов Н.') WHERE 'Никита Ульянов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Никита Шишканов', 'Шишканов Н.') WHERE 'Никита Шишканов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Николай Андрианов', 'Андрианов Н.') WHERE 'Николай Андрианов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Николай Елисеев', 'Елисеев Н.') WHERE 'Николай Елисеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Николай Кашников', 'Кашников Н.') WHERE 'Николай Кашников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Николай Петрович Николаев', 'Николаев Н.П.') WHERE 'Николай Петрович Николаев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Николай Сошин', 'Сошин Н.') WHERE 'Николай Сошин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Оганес Багдасарян', 'Багдасарян О.') WHERE 'Оганес Багдасарян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Одилхон Мадаминов-Ширинский', 'Мадаминов-Ширинский О.') WHERE 'Одилхон Мадаминов-Ширинский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Оксана Владимировна Дорошина', 'Дорошина О.В.') WHERE 'Оксана Владимировна Дорошина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Оксана Владимировна Тюсина', 'Тюсина О.В.') WHERE 'Оксана Владимировна Тюсина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Валентинович Гутников', 'Гутников О.В.') WHERE 'Олег Валентинович Гутников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Гутников', 'Гутников О.В.') WHERE 'Олег Гутников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Зайцев', 'Зайцев О.Р.') WHERE 'Олег Зайцев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Малахов', 'Малахов О.') WHERE 'Олег Малахов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Романович Зайцев', 'Зайцев О.Р.') WHERE 'Олег Романович Зайцев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олег Сурков', 'Сурков О.') WHERE 'Олег Сурков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олеся Петроль', 'Петроль О.') WHERE 'Олеся Петроль' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Олеся Степина', 'Степина О.') WHERE 'Олеся Степина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Александровна Огурцова', 'Огурцова О.А.') WHERE 'Ольга Александровна Огурцова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Власова', 'Власова О.') WHERE 'Ольга Власова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Жаркова', 'Жаркова О.') WHERE 'Ольга Жаркова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Игоревна Романова', 'Романова О.И.') WHERE 'Ольга Игоревна Романова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Огурцова', 'Огурцова О.А.') WHERE 'Ольга Огурцова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Павловна Плешанова', 'Плешанова О.П.') WHERE 'Ольга Павловна Плешанова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Плешанова', 'Плешанова О.П.') WHERE 'Ольга Плешанова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ольга Романова', 'Романова О.И.') WHERE 'Ольга Романова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Копылов', 'Копылов П.') WHERE 'Павел Копылов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Макаров', 'Макаров П.') WHERE 'Павел Макаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Марков', 'Марков П.') WHERE 'Павел Марков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Правящий', 'Правящий П.') WHERE 'Павел Правящий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Семенцов', 'Семенцов П.') WHERE 'Павел Семенцов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Сладков', 'Сладков П.') WHERE 'Павел Сладков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Тарасов', 'Тарасов П.') WHERE 'Павел Тарасов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Чистяков', 'Чистяков П.') WHERE 'Павел Чистяков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Павел Шефас', 'Шефас П.') WHERE 'Павел Шефас' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Пауль Кретчмар', 'Кретчмар П.') WHERE 'Пауль Кретчмар' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Петр Попов', 'Попов П.') WHERE 'Петр Попов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Полина Астапенко', 'Астапенко П.') WHERE 'Полина Астапенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Полина Владимировна Корнилина', 'Корнилина П.В.') WHERE 'Полина Владимировна Корнилина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Полина Ломакина', 'Ломакина П.') WHERE 'Полина Ломакина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Полина Напольская', 'Напольская П.') WHERE 'Полина Напольская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Радик Лотфуллин', 'Лотфуллин Р.') WHERE 'Радик Лотфуллин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Радик Рашитович Лугманов', 'Лугманов Р.Р.') WHERE 'Радик Рашитович Лугманов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Радислав Репин', 'Репин Р.') WHERE 'Радислав Репин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Радислав Репин', 'Репин Р.') WHERE 'Радислав Репин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Райнхард Борк', 'Борк Р.') WHERE 'Райнхард Борк' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рауль Сайфуллин', 'Сайфуллин Р.') WHERE 'Рауль Сайфуллин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рафаил Хафизов', 'Хафизов Р.') WHERE 'Рафаил Хафизов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рашид Уралович Сулейманов', 'Сулейманов Р.У.') WHERE 'Рашид Уралович Сулейманов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Регина Платонова', 'Платонова Р.') WHERE 'Регина Платонова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рената Франк', 'Франк Р.') WHERE 'Рената Франк' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Риккардо Кардилли', 'Кардилли Р.') WHERE 'Риккардо Кардилли' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Родион Гренадерский', 'Гренадерский Р.Д.') WHERE 'Родион Гренадерский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Родион Дмитриевич Гренадерский', 'Гренадерский Р.Д.') WHERE 'Родион Дмитриевич Гренадерский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Родион Макин', 'Макин Р.') WHERE 'Родион Макин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Родион Филиппов', 'Филиппов Р.') WHERE 'Родион Филиппов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Роман Сергеевич Бевзенко', 'Бевзенко Р.С.') WHERE 'Роман Сергеевич Бевзенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Роман Тараданов', 'Тараданов Р.') WHERE 'Роман Тараданов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Роман Ходыкин', 'Ходыкин Р.') WHERE 'Роман Ходыкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ростислав Романович Бевзенко', 'Бевзенко Р.Р.') WHERE 'Ростислав Романович Бевзенко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рудольф Иеринг', 'Иеринг Р.') WHERE 'Рудольф Иеринг' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Руслан Темурзиев', 'Темурзиев Р.') WHERE 'Руслан Темурзиев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рустам Галияхметов', 'Галияхметов Р.') WHERE 'Рустам Галияхметов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рустем Мифтахутдинов', 'Мифтахутдинов Р.Т.') WHERE 'Рустем Мифтахутдинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Рустем Тимурович Мифтахутдинов', 'Мифтахутдинов Р.Т.') WHERE 'Рустем Тимурович Мифтахутдинов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Саглар Борисовна Очирова', 'Очирова С.Б.') WHERE 'Саглар Борисовна Очирова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Светлана Валерьевна Апсаликова', 'Апсаликова С.В.') WHERE 'Светлана Валерьевна Апсаликова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Светлана Гвоздева', 'Гвоздева С.') WHERE 'Светлана Гвоздева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Светлана Юрьевна Сидельникова', 'Сидельникова С.Ю.') WHERE 'Светлана Юрьевна Сидельникова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Семен Степанов', 'Степанов С.') WHERE 'Семен Степанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергеей Васильевич Сарбаш', 'Сарбаш С.В.') WHERE 'Сергеей Васильевич Сарбаш' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Александрович Белов', 'Белов С.А.') WHERE 'Сергей Александрович Белов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Александрович Громов', 'Громов С.А.') WHERE 'Сергей Александрович Громов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Анашкин', 'Анашкин С.') WHERE 'Сергей Анашкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Будылин', 'Будылин С.Л.') WHERE 'Сергей Будылин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Васильевич Дедиков', 'Дедиков С.В.') WHERE 'Сергей Васильевич Дедиков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Викторович Стрембелев', 'Стрембелев С.В.') WHERE 'Сергей Викторович Стрембелев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Владимирович Трофимов', 'Трофимов С.В.') WHERE 'Сергей Владимирович Трофимов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Громов', 'Громов С.А.') WHERE 'Сергей Громов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Домнин', 'Домнин С.') WHERE 'Сергей Домнин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Ким', 'Ким С.') WHERE 'Сергей Ким' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Львович Будылин', 'Будылин С.Л.') WHERE 'Сергей Львович Будылин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Овсянников', 'Овсянников С.') WHERE 'Сергей Овсянников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Покровский', 'Покровский С.') WHERE 'Сергей Покровский' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Сарбаш', 'Сарбаш С.') WHERE 'Сергей Сарбаш' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Семенов', 'Семенов С.') WHERE 'Сергей Семенов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Сенников', 'Сенников С.') WHERE 'Сергей Сенников' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Стрембелев', 'Стрембелев С.В.') WHERE 'Сергей Стрембелев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Усоскин', 'Усоскин С.') WHERE 'Сергей Усоскин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Халатов', 'Халатов С.') WHERE 'Сергей Халатов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сергей Будылин', 'Будылин С.Л.') WHERE 'Сергей Будылин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Совет по кодификации', 'кодификации С.п.') WHERE 'Совет по кодификации' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'София Данилова', 'Данилова С.') WHERE 'София Данилова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Софья Пименова', 'Пименова С.') WHERE 'Софья Пименова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Софья Филиппова', 'Филиппова С.') WHERE 'Софья Филиппова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Станислав Александрович Гаранжа', 'Гаранжа С.А.') WHERE 'Станислав Александрович Гаранжа' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Станислав Александрович Смирнов', 'Смирнов С.А.') WHERE 'Станислав Александрович Смирнов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Станислав Егоркин', 'Егоркин С.') WHERE 'Станислав Егоркин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Станислав Медик', 'Медик С.') WHERE 'Станислав Медик' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Станислав Соболев', 'Соболев С.') WHERE 'Станислав Соболев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Сьеф ван Эрп', 'Эрп С.в.') WHERE 'Сьеф ван Эрп' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Тамара Зарандия', 'Зарандия Т.') WHERE 'Тамара Зарандия' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Тариел Артурович Саргсян', 'Саргсян Т.А.') WHERE 'Тариел Артурович Саргсян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Викторовна Драгунова', 'Драгунова Т.В.') WHERE 'Татьяна Викторовна Драгунова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Драгунова', 'Драгунова Т.В.') WHERE 'Татьяна Драгунова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Константиновна Андреева', 'Андреева Т.К.') WHERE 'Татьяна Константиновна Андреева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Краснова', 'Краснова Т.С.') WHERE 'Татьяна Краснова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Левкина', 'Левкина Т.') WHERE 'Татьяна Левкина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Николаевна Нешатаева', 'Нешатаева Т.Н.') WHERE 'Татьяна Николаевна Нешатаева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Рыжова', 'Рыжова Т.') WHERE 'Татьяна Рыжова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Сергеевна Краснова', 'Краснова Т.С.') WHERE 'Татьяна Сергеевна Краснова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Татьяна Станиславовна Бойко', 'Бойко Т.С.') WHERE 'Татьяна Станиславовна Бойко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Тим Лассен', 'Лассен Т.') WHERE 'Тим Лассен' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Тимофей Чистов', 'Чистов Т.') WHERE 'Тимофей Чистов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Тимур Аиткулов', 'Аиткулов Т.') WHERE 'Тимур Аиткулов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ульрих Хубер', 'Хубер У.') WHERE 'Ульрих Хубер' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Федор Архипов', 'Архипов Ф.') WHERE 'Федор Архипов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Федор Трофимов', 'Трофимов Ф.') WHERE 'Федор Трофимов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Филипп Вадимович Лучкин', 'Лучкин Ф.В.') WHERE 'Филипп Вадимович Лучкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Филипп Галушкин', 'Галушкин Ф.') WHERE 'Филипп Галушкин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Филипп Трамбицкий', 'Трамбицкий Ф.') WHERE 'Филипп Трамбицкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Франческо Паоло Патти', 'Патти Ф.П.') WHERE 'Франческо Паоло Патти' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Фриц Райхерт-Фасилидес', 'Райхерт-Фасилидес Ф.') WHERE 'Фриц Райхерт-Фасилидес' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Фёдор Селин', 'Селин Ф.') WHERE 'Фёдор Селин' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Хельмут Коциоль', 'Коциоль Х.') WHERE 'Хельмут Коциоль' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Чжеву Ли', 'Ли Ч.') WHERE 'Чжеву Ли' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Шай Джексон', 'Джексон Ш.') WHERE 'Шай Джексон' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эдуард Бершицкий', 'Бершицкий Э.') WHERE 'Эдуард Бершицкий' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эдуард Евстигнеев', 'Евстигнеев Э.') WHERE 'Эдуард Евстигнеев' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эли Гервиц', 'Гервиц Э.') WHERE 'Эли Гервиц' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эльвира Пономарева', 'Пономарева Э.') WHERE 'Эльвира Пономарева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эльдар Мамедов', 'Мамедов Э.') WHERE 'Эльдар Мамедов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эльза Азатян', 'Азатян Э.') WHERE 'Эльза Азатян' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Эрнеста Ипполитова', 'Ипполитова Э.') WHERE 'Эрнеста Ипполитова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлий Тай', 'Тай Ю.') WHERE 'Юлий Тай' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Байгушева', 'Байгушева Ю.') WHERE 'Юлия Байгушева' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Казаник', 'Казаник Ю.') WHERE 'Юлия Казаник' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Мазурова', 'Мазурова Ю.') WHERE 'Юлия Мазурова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Миронова', 'Миронова Ю.') WHERE 'Юлия Миронова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Михальчук', 'Михальчук Ю.') WHERE 'Юлия Михальчук' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Старченко', 'Старченко Ю.') WHERE 'Юлия Старченко' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юлия Сюльдина', 'Сюльдина Ю.') WHERE 'Юлия Сюльдина' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Борисович Фогельсон', 'Фогельсон Ю.Б.') WHERE 'Юрий Борисович Фогельсон' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Брисов', 'Брисов Ю.') WHERE 'Юрий Брисов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Валерьевич Южаков', 'Южаков Ю.В.') WHERE 'Юрий Валерьевич Южаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Заказнов', 'Заказнов Ю.Ю.') WHERE 'Юрий Заказнов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Кириллович Толстой', 'Толстой Ю.К.') WHERE 'Юрий Кириллович Толстой' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Фогельсон', 'Фогельсон Ю.Б.') WHERE 'Юрий Фогельсон' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Хандкаров', 'Хандкаров Ю.') WHERE 'Юрий Хандкаров' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Южаков', 'Южаков Ю.В.') WHERE 'Юрий Южаков' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Юрий Юрьевич Заказнов', 'Заказнов Ю.Ю.') WHERE 'Юрий Юрьевич Заказнов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Якуб Бисултанов', 'Бисултанов Я.') WHERE 'Якуб Бисултанов' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Яна Бутакова', 'Бутакова Я.') WHERE 'Яна Бутакова' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Яна Куташевская', 'Куташевская Я.') WHERE 'Яна Куташевская' = ANY(authors);
UPDATE articles SET authors = array_replace(authors, 'Ярослав Карнаков', 'Карнаков Я.') WHERE 'Ярослав Карнаков' = ANY(authors);